---
- name: Launch ec2
  ec2:
#    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
#    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
#    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "{{ region }}"
    group: "{{ security_group }}"
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_type }}"
    instance_profile_name: "{{ role }}" 
    image: "{{ ami }}"
    wait: yes
    exact_count: 1
    instance_tags:
      Application: "{{ Application }}"
      Creator: "{{ Creator }}"
      Description: "{{ Description }}"
      Name: "{{ Name }}"
      Owner: "{{ Owner }}"
      Technology: "{{ Technology }}"
    count_tag:
      Application: "{{ Application }}"
      Creator: "{{ Creator }}"
      Description: "{{ Description }}"
      Name: "{{ Name }}"
      Owner: "{{ Owner }}"
      Technology: "{{ Technology }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: "{{ yes_no }}"
  register: ec2_details

- name: Debug
  debug:
    msg: "{{ public_ip }}"
